# Generated by Django 6.0.3 on 2026-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_cadre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_vendeur',
            field=models.BooleanField(default=False),
        ),
    ]
